// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef NOTE_ENTITY_ODB_HXX
#define NOTE_ENTITY_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20200UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "NoteEntity.hpp"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // NoteEntity
  //
  template <>
  struct class_traits< ::NoteEntity >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::NoteEntity >
  {
    public:
    typedef ::NoteEntity object_type;
    typedef ::NoteEntity* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // NoteEntity
  //
  template <typename A>
  struct query_columns< ::NoteEntity, id_sqlite, A >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // active
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        bool,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    active_type_;

    static const active_type_ active;

    // timestamp
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::time_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    timestamp_type_;

    static const timestamp_type_ timestamp;

    // body
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    body_type_;

    static const body_type_ body;
  };

  template <typename A>
  const typename query_columns< ::NoteEntity, id_sqlite, A >::id_type_
  query_columns< ::NoteEntity, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::NoteEntity, id_sqlite, A >::active_type_
  query_columns< ::NoteEntity, id_sqlite, A >::
  active (A::table_name, "\"active\"", 0);

  template <typename A>
  const typename query_columns< ::NoteEntity, id_sqlite, A >::timestamp_type_
  query_columns< ::NoteEntity, id_sqlite, A >::
  timestamp (A::table_name, "\"timestamp\"", 0);

  template <typename A>
  const typename query_columns< ::NoteEntity, id_sqlite, A >::body_type_
  query_columns< ::NoteEntity, id_sqlite, A >::
  body (A::table_name, "\"body\"", 0);

  template <typename A>
  struct pointer_query_columns< ::NoteEntity, id_sqlite, A >:
    query_columns< ::NoteEntity, id_sqlite, A >
  {
  };

  template <>
  class access::object_traits_impl< ::NoteEntity, id_sqlite >:
    public access::object_traits< ::NoteEntity >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      long long id_value;
      bool id_null;

      // _active
      //
      long long _active_value;
      bool _active_null;

      // _timestamp
      //
      long long _timestamp_value;
      bool _timestamp_null;

      // _body
      //
      details::buffer _body_value;
      std::size_t _body_size;
      bool _body_null;

      std::size_t version;
    };

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&, bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&, const object_type&, sqlite::statement_kind);

    static void
    init (object_type&, const image_type&, database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    struct container_statement_cache_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static bool
    create_schema (database&, unsigned short pass, bool drop);

    public:
    static bool
    find_ (statements_type&, const id_type*);

    static void
    load_ (statements_type&, object_type&);
  };

  template <>
  class access::object_traits_impl< ::NoteEntity, id_common >:
    public access::object_traits_impl< ::NoteEntity, id_sqlite >
  {
  };

  // NoteEntity
  //
}

#include "NoteEntity-odb.ixx"

#include <odb/post.hxx>

#endif // NOTE_ENTITY_ODB_HXX
